# ============================================================================
#  MCKL/cmake/FindTBB.cmake
# ----------------------------------------------------------------------------
#  MCKL: Monte Carlo Kernel Library
# ----------------------------------------------------------------------------
#  Copyright (c) 2013-2016, Yan Zhou
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#    Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
#    Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS AS IS
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
# ============================================================================

# Find Intel Threading Building Blocks library
#
# This module can be used to find TBB headers and libraries
#
# The following variables are set
#
# TBB_FOUND                       - TRUE if TBB is found and work correctly
# TBB_INCLUDE_DIR                 - The directory containing TBB headers
# TBB_LINK_LIBRARIES              - TBB libraries that shall be linked to
# TBB_MALLOC_LINK_LIBRARIES       - TBB malloc libraries
# TBB_MALLOC_PROXY_LINK_LIBRARIES - TBB malloc proxy libraries
# TBB_DEFINITIONS                 - TBB compile time definitions
#
# The following variables affect the behavior of this module
#
# TBB_INC_PATH - The path CMake shall try to find headers first
# TBB_LIB_PATH - The path CMake shall try to find libraries first

IF(DEFINED TBB_FOUND)
    RETURN()
ENDIF(DEFINED TBB_FOUND)

FILE(READ ${CMAKE_CURRENT_LIST_DIR}/FindTBB.cpp TBB_TEST_SOURCE)

INCLUDE(FindThreads)

IF(NOT DEFINED TBB_LINK_LIBRARIES)
    FIND_LIBRARY(TBB_LINK_LIBRARIES_RELEASE_FOUND tbb
        PATHS ${TBB_LIB_PATH} ENV LIBRARY_PATH ENV LIB NO_DEFAULT_PATH)
    FIND_LIBRARY(TBB_LINK_LIBRARIES_RELEASE_FOUND tbb)
    FIND_LIBRARY(TBB_LINK_LIBRARIES_DEBUG_FOUND tbb_debug
        PATHS ${TBB_LIB_PATH} ENV LIBRARY_PATH ENV LIB NO_DEFAULT_PATH)
    FIND_LIBRARY(TBB_LINK_LIBRARIES_DEBUG_FOUND tbb_debug)
    IF(TBB_LINK_LIBRARIES_RELEASE_FOUND AND TBB_LINK_LIBRARIES_DEBUG_FOUND)
        SET(TBB_LINK_LIBRARIES
            optimized ${TBB_LINK_LIBRARIES_RELEASE_FOUND}
            debug ${TBB_LINK_LIBRARIES_DEBUG_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING "Link to TBB")
        SET(TBB_LINK_LIBRARIES_RELEASE ${TBB_LINK_LIBRARIES_RELEASE_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING "Link to TBB Release")
        SET(TBB_LINK_LIBRARIES_DEBUG ${TBB_LINK_LIBRARIES_DEBUG_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING "Link to TBB Debug")
        MESSAGE(STATUS "Found TBB libraries: ${TBB_LINK_LIBRARIES}")
    ELSEIF(TBB_LINK_LIBRARIES_RELEASE_FOUND)
        SET(TBB_LINK_LIBRARIES ${TBB_LINK_LIBRARIES_RELEASE_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING "Link to TBB")
        SET(TBB_LINK_LIBRARIES_RELEASE ${TBB_LINK_LIBRARIES_RELEASE_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING "Link to TBB Release")
        MESSAGE(STATUS "Found TBB libraries: ${TBB_LINK_LIBRARIES}")
    ELSE(TBB_LINK_LIBRARIES_RELEASE_FOUND AND TBB_LINK_LIBRARIES_DEBUG_FOUND)
        MESSAGE(STATUS "NOT Found TBB libraries")
    ENDIF(TBB_LINK_LIBRARIES_RELEASE_FOUND AND TBB_LINK_LIBRARIES_DEBUG_FOUND)
ENDIF(NOT DEFINED TBB_LINK_LIBRARIES)

IF(NOT DEFINED TBB_MALLOC_LINK_LIBRARIES)
    FIND_LIBRARY(TBB_MALLOC_LINK_LIBRARIES_RELEASE_FOUND tbbmalloc
        PATHS ${TBB_LIB_PATH} ENV LIBRARY_PATH ENV LIB NO_DEFAULT_PATH)
    FIND_LIBRARY(TBB_MALLOC_LINK_LIBRARIES_RELEASE_FOUND tbbmalloc)
    FIND_LIBRARY(TBB_MALLOC_LINK_LIBRARIES_DEBUG_FOUND tbbmalloc_debug
        PATHS ${TBB_LIB_PATH} ENV LIBRARY_PATH ENV LIB NO_DEFAULT_PATH)
    FIND_LIBRARY(TBB_MALLOC_LINK_LIBRARIES_DEBUG_FOUND tbbmalloc_debug)
    IF(TBB_MALLOC_LINK_LIBRARIES_RELEASE_FOUND AND
            TBB_MALLOC_LINK_LIBRARIES_DEBUG_FOUND)
        SET(TBB_MALLOC_LINK_LIBRARIES
            optimized ${TBB_MALLOC_LINK_LIBRARIES_RELEASE_FOUND}
            debug ${TBB_MALLOC_LINK_LIBRARIES_DEBUG_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING
            "Link to TBB malloc")
        SET(TBB_MALLOC_LINK_LIBRARIES_RELEASE
            ${TBB_MALLOC_LINK_LIBRARIES_RELEASE_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING
            "Link to TBB malloc Release")
        SET(TBB_MALLOC_LINK_LIBRARIES_DEBUG
            ${TBB_MALLOC_LINK_LIBRARIES_DEBUG_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING
            "Link to TBB malloc Debug")
        MESSAGE(STATUS
            "Found TBB malloc libraries: ${TBB_MALLOC_LINK_LIBRARIES}")
    ELSEIF(TBB_MALLOC_LINK_LIBRARIES_RELEASE_FOUND)
        SET(TBB_MALLOC_LINK_LIBRARIES
            ${TBB_MALLOC_LINK_LIBRARIES_RELEASE_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING
            "Link to TBB malloc")
        SET(TBB_MALLOC_LINK_LIBRARIES_RELEASE
            ${TBB_MALLOC_LINK_LIBRARIES_RELEASE_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING
            "Link to TBB malloc Release")
        MESSAGE(STATUS
            "Found TBB malloc libraries: ${TBB_MALLOC_LINK_LIBRARIES}")
    ELSE(TBB_MALLOC_LINK_LIBRARIES_RELEASE_FOUND AND
            TBB_MALLOC_LINK_LIBRARIES_DEBUG_FOUND)
        MESSAGE(STATUS "NOT Found TBB malloc libraries")
    ENDIF(TBB_MALLOC_LINK_LIBRARIES_RELEASE_FOUND AND
        TBB_MALLOC_LINK_LIBRARIES_DEBUG_FOUND)
ENDIF(NOT DEFINED TBB_MALLOC_LINK_LIBRARIES)

IF(NOT DEFINED TBB_MALLOC_PROXY_LINK_LIBRARIES)
    FIND_LIBRARY(TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE_FOUND
        tbbmalloc_proxy
        PATHS ${TBB_LIB_PATH} ENV LIBRARY_PATH ENV LIB NO_DEFAULT_PATH)
    FIND_LIBRARY(TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE_FOUND
        tbbmalloc_proxy)
    FIND_LIBRARY(TBB_MALLOC_PROXY_LINK_LIBRARIES_DEBUG_FOUND
        tbbmalloc_proxy_debug
        PATHS ${TBB_LIB_PATH} ENV LIBRARY_PATH ENV LIB NO_DEFAULT_PATH)
    FIND_LIBRARY(TBB_MALLOC_PROXY_LINK_LIBRARIES_DEBUG_FOUND
        tbbmalloc_proxy_debug)
    IF(TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE_FOUND AND
            TBB_MALLOC_PROXY_LINK_LIBRARIES_DEBUG_FOUND)
        SET(TBB_MALLOC_PROXY_LINK_LIBRARIES
            optimized ${TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE_FOUND}
            debug ${TBB_MALLOC_PROXY_LINK_LIBRARIES_DEBUG_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING
            "Link to TBB malloc proxy")
        SET(TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE
            ${TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING
            "Link to TBB malloc proxy Release")
        SET(TBB_MALLOC_PROXY_LINK_LIBRARIES_DEBUG
            ${TBB_MALLOC_PROXY_LINK_LIBRARIES_DEBUG_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING
            "Link to TBB malloc proxy Debug")
        MESSAGE(STATUS
            "Found TBB malloc proxy libraries: ${TBB_MALLOC_PROXY_LINK_LIBRARIES}")
    ELSEIF(TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE_FOUND)
        SET(TBB_MALLOC_PROXY_LINK_LIBRARIES
            ${TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING
            "Link to TBB malloc proxy")
        SET(TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE
            ${TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE_FOUND}
            ${CMAKE_THREAD_LIBS_INIT} CACHE STRING
            "Link to TBB malloc proxy Release")
        MESSAGE(STATUS
            "Found TBB malloc proxy libraries: ${TBB_MALLOC_PROXY_LINK_LIBRARIES}")
    ELSE(TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE_FOUND AND
            TBB_MALLOC_PROXY_LINK_LIBRARIES_DEBUG_FOUND)
        MESSAGE(STATUS "NOT Found TBB malloc proxy libraries")
    ENDIF(TBB_MALLOC_PROXY_LINK_LIBRARIES_RELEASE_FOUND AND
        TBB_MALLOC_PROXY_LINK_LIBRARIES_DEBUG_FOUND)
ENDIF(NOT DEFINED TBB_MALLOC_PROXY_LINK_LIBRARIES)

IF(NOT DEFINED TBB_INCLUDE_DIR)
    FIND_PATH(TBB_INCLUDE_DIR tbb/tbb.h
        PATHS ${TBB_INC_PATH} ENV CPATH NO_DEFAULT_PATH)
    FIND_PATH(TBB_INCLUDE_DIR tbb/tbb.h)
    IF(TBB_INCLUDE_DIR)
        MESSAGE(STATUS "Found TBB headers: ${TBB_INCLUDE_DIR}")
    ELSE(TBB_INCLUDE_DIR)
        MESSAGE(STATUS "NOT Found TBB headers")
    ENDIF(TBB_INCLUDE_DIR)
ENDIF(NOT DEFINED TBB_INCLUDE_DIR)

IF(TBB_LINK_LIBRARIES AND TBB_INCLUDE_DIR)
    SET(TBB_BASIC_FOUND TRUE)
ELSE(TBB_LINK_LIBRARIES AND TBB_INCLUDE_DIR)
    SET(TBB_BASIC_FOUND FALSE)
ENDIF(TBB_LINK_LIBRARIES AND TBB_INCLUDE_DIR)

IF(TBB_BASIC_FOUND)
    SET(SAFE_CMAKE_REQUIRED_INCLUDES  ${CMAKE_REQUIRED_INCLUDES})
    SET(SAFE_CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES})
    SET(CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES}
        ${TBB_INCLUDE_DIR})
    IF(TBB_LINK_LIBRARIES_DEBUG)
        SET(CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES}
            ${TBB_LINK_LIBRARIES_DEBUG})
    ELSE(TBB_LINK_LIBRARIES_DEBUG)
        SET(CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES}
            ${TBB_LINK_LIBRARIES})
    ENDIF(TBB_LINK_LIBRARIES_DEBUG)
    INCLUDE(CheckCXXSourceRuns)
    CHECK_CXX_SOURCE_RUNS("${TBB_TEST_SOURCE}" TBB_FOUND)
    IF(TBB_FOUND)
        MESSAGE(STATUS "Found TBB")
    ELSE(TBB_FOUND)
        MESSAGE(STATUS "NOT Found TBB")
    ENDIF(TBB_FOUND)
    SET(CMAKE_REQUIRED_INCLUDES ${SAFE_CMAKE_REQUIRED_INCLUDES})
    SET(CMAKE_REQUIRED_LIBRARIES ${SAFE_CMAKE_REQUIRED_LIBRARIES})
ELSE(TBB_BASIC_FOUND)
    MESSAGE(STATUS "NOT Found TBB")
    SET(TBB_FOUND FALSE CACHE BOOL "NOT Found TBB")
ENDIF(TBB_BASIC_FOUND)
